language: go

sudo: false

go:
  - 1.8
  - tip

install:
  # Install our tracked dependencies
  - go get -t ./...
  - curl -L https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz -o /tmp/glide.tar.gz
  - mkdir ../glide && cd ../glide && tar -xzf /tmp/glide.tar.gz && export PATH=$PATH:$PWD/linux-amd64/ && cd ../cayley
  - glide install

  # Google App Engine dependencies
  #  - cd ..
  #  - wget https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.40.zip
  #  - unzip -q go_appengine_sdk_linux_amd64-1.9.40.zip
  #  - export PATH=$PATH:$PWD/go_appengine/
  #  - cd cayley

script:
  - go test -v $(go list ./... | grep -v vendor/)
  #  - goapp test -v ./graph/gaedatastore

matrix:
  allow_failures:
    - go: tip
