language: go

addons:
  apt:
    packages:
      - snapd

go:
  - "1.13.x"
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - sudo snap install snapcraft --classic
  - go mod download
  - go run cmd/download_ui/download_ui.go

cache:
  directories:
    - $GOPATH/pkg/mod

script:
  - CGO_ENABLED=0 go build -o /tmp/cayley ./cmd/cayley
  - go run github.com/gobuffalo/packr/v2/packr2
  - git checkout -- ./packrd/dummy.go
  - |
    if [[ $TRAVIS_GO_VERSION =~ ^1\.13 ]]; then
      go get -u golang.org/x/lint/golint && bash lint.sh
    else
      # run go vet for other go versions, but do not fail
      go vet ./... ||Â true
    fi
  - go test -v ./...

after_success:
  - test -n "$TRAVIS_TAG" && echo "$SNAP_TOKEN" > /tmp/snap.login && snapcraft login --with /tmp/snap.login

deploy:
  - provider: script
    skip_cleanup: true
    script: git status && curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux && $TRAVIS_GO_VERSION =~ ^1\.13
