language: go

sudo: false

go:
  - 1.4
  - 1.5
  - tip

install:
  # Install our tracked dependencies
  - go get github.com/tools/godep
  - godep restore

  # Google App Engine dependencies
  - cd ..
  - wget https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.23.zip
  - unzip -q go_appengine_sdk_linux_amd64-1.9.23.zip
  - export PATH=$PATH:$PWD/go_appengine/
  - cd cayley

script:
  - go test -v ./...
  - goapp test -v ./graph/gaedatastore

