language: go

sudo: false

go:
  - "1.10"
  - "1.11"
  - tip

install:
  # Install our tracked dependencies
  - go get -t ./...
  - mkdir ../dep && curl -L https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o ../dep/dep && chmod +x ../dep/dep && export PATH=$PATH:$PWD/../dep/
  - dep ensure --vendor-only

  # Google App Engine dependencies
  #  - cd ..
  #  - wget https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.40.zip
  #  - unzip -q go_appengine_sdk_linux_amd64-1.9.40.zip
  #  - export PATH=$PATH:$PWD/go_appengine/
  #  - cd cayley

script:
  - go test -v ./...
  #  - goapp test -v ./graph/gaedatastore

matrix:
  allow_failures:
    - go: tip
