language: go

sudo: false

go:
  - 1.3
  - 1.4
  - tip

install:
  - go get github.com/badgerodon/peg
  - go get github.com/barakmich/glog
  - go get github.com/cznic/mathutil
  - go get github.com/julienschmidt/httprouter
  - go get github.com/petar/GoLLRB/llrb
  - go get github.com/peterh/liner
  - go get github.com/robertkrimen/otto
  - go get github.com/russross/blackfriday
  - go get github.com/syndtr/goleveldb/leveldb
  - go get github.com/syndtr/goleveldb/leveldb/cache
  - go get github.com/syndtr/goleveldb/leveldb/iterator
  - go get github.com/syndtr/goleveldb/leveldb/opt
  - go get github.com/syndtr/goleveldb/leveldb/util
  - go get github.com/boltdb/bolt
  - go get gopkg.in/mgo.v2
  - go get gopkg.in/mgo.v2/bson
  - go get code.google.com/p/go-uuid/uuid

  # Google App Engine dependencies
  - wget https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.18.zip
  - unzip -q go_appengine_sdk_linux_amd64-1.9.18.zip
  - export PATH=$PATH:$PWD/go_appengine/

script: 
  - go test -v ./...
  - goapp test -v ./graph/gaedatastore

