language: go

go:
  - 1.2
  - 1.3
  - tip

install:
  - go get github.com/badgerodon/peg
  - go get github.com/barakmich/glog
  - go get github.com/julienschmidt/httprouter
  - go get github.com/petar/GoLLRB/llrb
  - go get github.com/peterh/liner
  - go get github.com/robertkrimen/otto
  - go get github.com/russross/blackfriday
  - go get github.com/syndtr/goleveldb/leveldb
  - go get github.com/syndtr/goleveldb/leveldb/cache
  - go get github.com/syndtr/goleveldb/leveldb/iterator
  - go get github.com/syndtr/goleveldb/leveldb/opt
  - go get github.com/syndtr/goleveldb/leveldb/util
  - go get gopkg.in/mgo.v2
  - go get gopkg.in/mgo.v2/bson

script: go test -v ./...

